//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nedvigimost.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Недвижимость_КолиEntities : DbContext
    {
        public Недвижимость_КолиEntities()
            : base("name=Недвижимость_КолиEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Application> Application { get; set; }
        public virtual DbSet<Cities> Cities { get; set; }
        public virtual DbSet<Contract> Contract { get; set; }
        public virtual DbSet<Property_type> Property_type { get; set; }
        public virtual DbSet<Real_estate> Real_estate { get; set; }
        public virtual DbSet<Report> Report { get; set; }
        public virtual DbSet<Request_for_an_appraiser> Request_for_an_appraiser { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
