//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nedvigimost.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Real_estate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Real_estate()
        {
            this.Application = new HashSet<Application>();
        }
    
        public int id { get; set; }
        public int IdProperty_type { get; set; }
        public int IdCities { get; set; }
        public string Address { get; set; }
        public string Squarе { get; set; }
        public Nullable<decimal> Price_on_sale { get; set; }
        public Nullable<decimal> Appraiser_price { get; set; }
        public int IdUsers { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Application> Application { get; set; }
        public virtual Cities Cities { get; set; }
        public virtual Property_type Property_type { get; set; }
        public virtual Users Users { get; set; }
    }
}
